<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="lidar_radius" value="0.1"/>
    <xacro:property name="lidar_length" value="0.1"/>

    <link name="${robot_name}/lidar_link">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                    <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="0.1" r="${lidar_radius}" l="${lidar_length}" 
                                o_xyz="0 0 0" o_rpy="0 0 0"/>
    </link>
    <joint name="${robot_name}/laser_joint" type="fixed">
        <parent link="${robot_name}/base_link"/>
        <child link="${robot_name}/lidar_link"/>
        <origin xyz="0.0 0.0 ${base_height + (lidar_length/2)}" rpy="0.0 0.0 0.0"/>
        <axis xyz="0.0 1.0 0.0"/>
    </joint>

</robot>
